# azure-pipelines.yml in RepoA (Primary Repository)

trigger:
  branches:
    include:
      - main
      - pip1

pool:
  name: default  # Use a valid VM image like 'ubuntu-latest'

resources:
  repositories:
    - repository: RepoB
      type: github
      name: Shrutidhanawade/Newdemo-27-8-2024  # Correct GitHub repository name (org/repo)
      ref: pip1  # Branch to pull from RepoB
      endpoint: Shrutidhanawade  # GitHub service connection name

steps:
# Checkout the primary repository (RepoA)
- checkout: self
  displayName: 'Checkout RepoA (Primary Repository)'

# Checkout the secondary repository (RepoB)
- checkout: RepoB
  displayName: 'Checkout RepoB (Secondary Repository)'

# Build and test Java code in RepoA using Maven
- script: |
    echo "Building RepoB"
    cd $(Build.SourcesDirectory)/RepoA/Newdemo-27-8-2024/
     javac HelloWorld.java
    
    echo "Listing files in RepoA:"
    ls -la
  displayName: 'Build and Test RepoA'

# Build and test Java code in RepoB using Maven
- script: |
    echo "Building RepoB"
    cd $(Build.SourcesDirectory)/RepoB/Newdemo-27-8-2024/
    javac HelloWorld.java
    echo "Listing files in RepoB:"
    ls -la
  displayName: 'Build and Test RepoB'
