# azure-pipelines.yml in RepoA (Primary Repository)

trigger:
  branches:
    include:
      - main
      

pool:
  name: default  # Use a valid VM image like 'ubuntu-latest'

resources:
  repositories:
    - repository: RepoB
      type: github
      name: Shrutidhanawade/dotnet  # Correct GitHub repository name (org/repo)
      ref: main  # Branch to pull from RepoB
      endpoint: Shrutidhanawade  # GitHub service connection name

steps:
# Checkout the primary repository (RepoA)
- checkout: self
  displayName: 'Checkout RepoA (Primary Repository)'

# Checkout the secondary repository (RepoB)
- checkout: RepoB
  displayName: 'Checkout RepoB (Secondary Repository)'

# Build and test Java code in RepoA using Maven
- script: |
    echo "Building RepoB"
    cd $(Build.SourcesDirectory)/Newdemo-27-8-2024/
     javac HelloWorld.java
    
    echo "Listing files in RepoA:"
    ls -la
  displayName: 'Build and Test RepoA'
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
# Build and test Java code in RepoB using Maven
- script: |
    echo "Building RepoB"
    cd $(Build.SourcesDirectory)/dotnet/HelloWorldApp/
    dotnet build HelloWorldApp.csproj --configuration Release
    echo "Listing files in RepoB:"
    ls -la
  displayName: 'Build and Test RepoB'
